"""add county details

Revision ID: 178db8037fb6
Revises: 4ee2a5ca8852
Create Date: 2025-06-11 16:08:52.594218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '178db8037fb6'
down_revision = '4ee2a5ca8852'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school_learners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('county', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school_learners', schema=None) as batch_op:
        batch_op.drop_column('county')

    # ### end Alembic commands ###
